set-option -g history-limit 50000

# --- amux tmux hook (begin) ---
set -g focus-events on
set -g @amux_bin "amux"
set-hook -g pane-focus-in "run-shell \"#{@amux_bin} event tmux focus --pane-id \\\"#{pane_id}\\\" --cwd \\\"#{pane_current_path}\\\" --tmux-session \\\"#{session_name}\\\" --tmux-window \\\"#{window_name}\\\" --tmux-client \\\"#{client_name}\\\"\""
# --- amux tmux hook (end) ---
