#!/usr/bin/env bash

# environment
cd ~/src/shopymate
alias sw="cd ~/src/shopymate && workon twiggle"
alias tw="cd ~/src/twiggle && workon twiggle"

# work
alias modelvalidate="python -m elef.model.cli validate "
alias mq=' python -m elef.cmd_tools '
alias mc=' python -m elef.model.cli '
