#!/usr/bin/python3

from urllib.parse import urlencode 
from sys import stdin
from sys import argv

host=argv[1]
parameter=argv[2]

for line in stdin:
    line = line.strip()
    print(host + "?" + urlencode({parameter: line}))

