#!/bin/bash
#
# Open the specified file on GitHub. It will use the master branch by default:
#
#   repo -f app/controllers/application_controller.rb
#
# Specify a different branch:
#
#   repo -b another-branch -f app/controllers/application_controller.rb

if git rev-parse --show-toplevel > /dev/null 2>&1; then
  echo "Opening on Github..."

  BRANCH=$(git rev-parse --abbrev-ref HEAD)

  while getopts ":b:f:" option
  do
    case "$option" in
      b) BRANCH=$OPTARG;;
      f) FILEPATH=$OPTARG;;
    esac
  done

  # Get the repository root directory
  REPO_ROOT=$(git rev-parse --show-toplevel)

  # **Changed**: Use git ls-files to get the relative path
  RELATIVE_FILEPATH=$(git ls-files --full-name "$FILEPATH")

  BASE=$(git config --get remote.origin.url | sed s/\\.git// | sed 's/:/\//' | sed 's/.*github.com/https:\/\/github.com/')
  URL="$BASE/blob/$BRANCH/$RELATIVE_FILEPATH"

  if which xdg-open > /dev/null
  then
    xdg-open $URL
  elif which gnome-open > /dev/null
  then
    gnome-open $URL
  elif which open > /dev/null
  then
    open $URL
  fi
  echo "Opened $URL"
else
  echo "Not a git repo"
fi
