#!/bin/bash
set -e

case "$1" in
  "kill")
    echo The first argument is 'kill', killing and removing container
    docker rm -f my_notebook
    ;;
  "open")
    open http://localhost:8888/?token=foo
    ;;
  "help")
    echo "Run jupyter-notebook [kill|open]" 
    echo "Running with no arguments will start a new container with jupyter lab" 
    ;;
  *)
    echo Running docker image: jupyter/scipy-notebook, mounted ~/jupyter_workspace into the container
    echo "The first argument != 'kill', running server (run 'jupyter-server kill' to kill it)"
    docker run -d -v  ~/jupyter_workspace:/home/jovyan/ --name my_notebook -e JUPYTER_TOKEN=foo  -p 8888:8888  jupyter/scipy-notebook
    echo Waiting to start
    sleep 1
    open http://localhost:8888/?token=foo
    ;;
esac


